"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta

from pathlib import Path

# ... باقي كود جينغو الافتراضي يبدأ من هنا
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!2+=w8f7^7$)35@-+ch+2ermweaat-9vn1&#0*)lrt*0hn!#-0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken', # نظام المصادقة المستخدم لدينا
    'drf_spectacular', # الحزمة الجديدة
    'wallet',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # يجب أن تكون في الأعلى
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

SPECTACULAR_SETTINGS = {
    'TITLE': 'Digital Wallet API',
    'DESCRIPTION': 'نظام خلفي متكامل للمحفظة الرقمية يدعم الحسابات، العمليات المالية المحمية، وصرف العملات.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # تفعيل واجهة الأمان لإدخال الـ Token في صفحة Swagger
    'SECURITY': [{
        'TokenAuth': []
    }],
    'COMPONENT_SPLIT_REQUEST': True,
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'nabil.sqlite3', # تأكد أن هذا الاسم مطابق تماماً لملفك الفعلي
    }
}
CORS_ALLOW_ALL_ORIGINS = True
REST_FRAMEWORK = {
    # تعيين المحرك الافتراضي للـ Schema
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    # إعداد نظام المصادقة بالـ Token الذي بنينا عليه التطبيق
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
                   'rest_framework_simplejwt.authentication.JWTAuthentication',

    ],
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

SIMPLE_JWT = {
    # ⏱️ عمر الـ Access Token (الرمز المستخدم لتصريح العمليات المالية الفورية)
    # نوصي بـ 15 دقيقة في بيئة الإنتاج، أو 5 دقائق لأغراض الفحص والاختبار السريع
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=3),
    
    # ⏱️ عمر الـ Refresh Token (الرمز المستخدم لتوليد Access Token جديد تلقائياً دون تسجيل خروج)
    # نوصي بـ 7 أيام ليظل المستخدم مسجلاً دخوله بشكل مريح على جهازه
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    
    # تدوير التوكنات لزيادة الأمان
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

SESSION_COOKIE_AGE = 180  

# 💻 جعل الجلسة تنتهي تلقائياً فور إغلاق المستخدم للمتصفح
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 🔄 تحديث عمر الجلسة تلقائياً مع كل حركة أو نشاط يقوم به المستخدم (لعدم طرده أثناء الاستخدام النشط)
SESSION_SAVE_EVERY_REQUEST = True